go_import_path: github.com/minio/minio-operator

language: go

services:
  - docker

# this ensures PRs based on a local branch are not built twice
# the downside is that a PR targeting a different branch is not built
# but as a workaround you can add the branch to this list
branches:
  only:
    - master

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env:
        - ARCH=x86_64
        - CGO_ENABLED=0
        - GO111MODULE=on
        - GOPROXY=https://proxy.golang.org
      go: 1.12.x
      script:
        - diff -au <(gofmt -s -d pkg) <(printf "")
        - make verify

before_script:
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/8361
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'; fi
